### PR TITLE
Color events based on hash of ID

### LINKED ISSUE #11: Differentiate events by color
Currently all events use the same blue color for session blocks on the timetable and schedule blocks on the overview card. 

This is confusing to users. We should use different colors for different events.

I propose using a color based on the hash of the ID of the event.

### PR DESCRIPTION
**Pull request by keyansheng**
Resolves #11

Event colors are dynamic and Tailwind is unable to generate classes for them at build time, so inline styles or other methods are needed to apply dynamically generated colors at runtime

https://v2.tailwindcss.com/docs/just-in-time-mode#arbitrary-value-support

- [x] generate and apply color based on event ID
- [x] adjust opacity based on isActive and hover states

image

### CODE REVIEW

**Comment by NhatMinh0208** [comment]
@keyansheng seems like session blocks on the calendar are not colored yet - can you apply the same colors from the event tab to the calendar?

**Comment by NhatMinh0208** [comment]
It will be somewhat more complicated because you need to handle events that are from followed users. I think a global color map might work here?

**Comment by keyansheng** [comment]
> @keyansheng seems like session blocks on the calendar are not colored yet - can you apply the same colors from the event tab to the calendar?

Oops, I think I totally missed the blocks on the actual timetable since I didn't scroll to see them

**Comment by NhatMinh0208** [comment]
Sorry for the delay, checking this now

**Pull request merged**
