### PR TITLE
 Add testing to application and create initial set of tests

### LINKED ISSUE #19: Add testing to application and create initial set of tests
Right now, there is no automatic testing for the app. (oof)

To prepare for Apollo 11, we need to add a testing framework and some initial tests to cover most of the code.

We plan to use Jest as our testing framework.

Every single component in our app is a function, so there shouldn't be too many obstacles.

### PR DESCRIPTION
**Pull request by keyansheng**
Resolves #19

### CODE REVIEW

**Comment by keyansheng** [comment]
Right now the first 2 tests depend on the current state of the production database, and would fail if the data in the production database is changed

**Comment by NhatMinh0208** [comment]
yeah this is definitely not good testing practice.

probably can just remove those for now

**Comment by keyansheng** [comment]
maybe we could use `beforeEach` to set up the database before each test

https://jestjs.io/docs/setup-teardown

**Comment by NhatMinh0208** [comment]
should be `beforeAll` since we are just setting up the database once for all the database tests

alternatively we can just set up a dev database, then we wouldn’t have to worry about this

**Comment by NhatMinh0208** [comment]
looks good enough, going to merge once and then we can merge again when we have more tests

**Pull request merged**
